
// Search
export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';
export const SEARCH_VIDEO_START = 'SEARCH_VIDEO_START';
export const SEARCH_VIDEO_SUCCESS = 'SEARCH_VIDEO_SUCCESS';
export const SEARCH_VIDEO_FAILURE = 'SEARCH_VIDEO_FAILURE';
export const SET_INSPECTED_VIDEO_INDEX = 'SET_INSPECTED_VIDEO_INDEX';